name: Production Deployment Example

on:
  push:
    branches:
      - main

env:
  ENVIRONMENT: production

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: us-east-1

      - name: Deploy to Production
        run: |
          terraform init
          terraform validate
          terraform apply -auto-approve \
            -var-file=terraform.tfvars${{ env.ENVIRONMENT }}

