name: Setup Repository Environments & Branch Protections

on:
  workflow_dispatch:

jobs:
  setup-environments:
    runs-on: ubuntu-latest
    steps:
      - name: Create Development Environment
        run: |
          curl -L -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/environments/development \
            -d '{
              "wait_timer": 0,
              "reviewers": [],
              "deployment_branch_policy": {
                "protected_branches": false,
                "custom_branch_policies": true
              }
            }'

      - name: Create Staging Environment
        run: |
          curl -L -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/environments/staging \
            -d '{
              "wait_timer": 0,
              "reviewers": [],
              "deployment_branch_policy": {
                "protected_branches": false,
                "custom_branch_policies": true
              }
            }'

      - name: Create Production Environment
        run: |
          curl -L -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/environments/production \
            -d '{
              "wait_timer": 300,
              "reviewers": [{"type": "User", "id": ${{ github.actor_id }}}],
              "deployment_branch_policy": {
                "protected_branches": true,
                "custom_branch_policies": false
              }
            }'

  setup-branch-protections:
    needs: setup-environments
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, "feature/*", "workflow/*", "development", "staging"]
    steps:
      - name: Setup Branch Protection for ${{ matrix.branch }}
        run: |
          curl -L -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/branches/${{ matrix.branch }}/protection \
            -d '{
              "required_status_checks": {
                "strict": true,
                "contexts": ["terraform-plan", "terraform-apply"]
              },
              "enforce_admins": true,
              "required_pull_request_reviews": {
                "dismiss_stale_reviews": true,
                "require_code_owner_reviews": false,
                "required_approving_review_count": 1,
                "require_last_push_approval": false
              },
              "restrictions": null,
              "required_linear_history": false,
              "allow_force_pushes": false,
              "allow_deletions": false,
              "block_creations": false,
              "required_conversation_resolution": true,
              "lock_branch": false,
              "allow_fork_syncing": true
            }'

