name: Use Reusable Terraform Apply

on:
  push:
    branches:
    - main
#     paths:
#     - 'terraform/**'
#     - '.github/workflows/use-terraform-apply-v1.yaml'

jobs:
  call-terraform-apply:
    uses: ./.github/workflows/terraform-apply-v1.yaml
    with:
      environment: development
      region: us-east-1
    secrets:
      oidc_role: ${{ secrets.OIDC_ROLE_ARN }}

