name: Use Reusable Terraform Plan

on:
  push:
    branches:
    - main
    # paths:
    # - '**/terraform/**'
    # - '.github/workflows/terraform-plan-v1.yml'

jobs:
  call-terraform-plan:
    uses: ./.github/workflows/terraform-plan-v1.yaml
    with:
      environment: development
      region: us-east-1
    secrets:
      oidc_role: ${{ secrets.OIDC_ROLE_ARN }}

