name: Call Reusable Terraform Plan Workflow

on:
  push:
    branches:
    - main
    paths:
    - 'terraform/**'
    - '.github/workflows/terraform-plan-v1.yaml'

  workflow_dispatch:

jobs:
  call-terraform-plan:
    uses: ./.github/workflows/terraform-plan-v1.yaml
    with:
      environment: development
      region: us-east-1
    secrets:
      oidc_role: ${{ secrets.OIDC_ROLE_ARN }}
      github_token: ${{ secrets.GITHUB_TOKEN }}

